name: push_notification_chat
description: A simple chat app with push notifications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_messaging: ^15.2.4
  socket_io_client: ^2.0.3
  hive: ^2.2.3
  path_provider: ^2.1.1
  firebase_core: ^2.24.2

flutter:
  uses-material-design: true
